package com.donalevans;

import java.util.ArrayList;
import java.util.List;

import static com.donalevans.InjuryDescriptionStrings.*;

public enum InjuryType {
  ANOSMIA(ANOSMIA_DESCRIPTION),
  BLINDNESS(BLINDNESS_DESCRIPTION),
  BLISTERS(BLISTERS_DESCRIPTION),
  BRAIN_INJURY(BRAIN_INJURY_DESCRIPTION),
  BROKEN_ARM(BROKEN_ARM_DESCRIPTION),
  BROKEN_LEG(BROKEN_LEG_DESCRIPTION),
  BROKEN_NOSE(BROKEN_NOSE_DESCRIPTION),
  BROKEN_RIBS(BROKEN_RIBS_DESCRIPTION),
  CARDIAC_INJURY(CARDIAC_INJURY_DESCRIPTION),
  DEAFNESS(DEAFNESS_DESCRIPTION),
  DESTROYED_FOOT_OR_LEG(DESTROYED_FOOT_OR_LEG_DESCRIPTION),
  DESTROYED_HAND(DESTROYED_HAND_DESCRIPTION),
  FIRST_DEGREE_BURNS(FIRST_DEGREE_BURNS_DESCRIPTION),
  FLASH_BURNS(FLASH_BURNS_DESCRIPTION),
  FOURTH_DEGREE_BURNS(FOURTH_DEGREE_BURNS_DESCRIPTION),
  FROSTBITTEN_FOOT(FROSTBITTEN_FOOT_DESCRIPTION),
  FROSTBITTEN_HAND(FROSTBITTEN_HAND_DESCRIPTION),
  GROIN_INJURY(GROIN_INJURY_DESCRIPTION),
  HAIR_LOSS_AND_COSMETIC_DAMAGE(HAIR_LOSS_AND_COSMETIC_DAMAGE_DESCRIPTION),
  HAMSTRUNG(HAMSTRUNG_DESCRIPTION),
  HORRIBLE_DISFIGUREMENT(HORRIBLE_DISFIGUREMENT_DESCRIPTION),
  INAPPROPRIATE_VOLUME(INAPPROPRIATE_VOLUME_DESCRIPTION),
  INDEFINITE_MADNESS(INDEFINITE_MADNESS_DESCRIPTION),
  INFLAMMATION(INFLAMMATION_DESCRIPTION),
  INTERNAL_INJURY(INTERNAL_INJURY_DESCRIPTION),
  KIDNEY_FAILURE(KIDNEY_FAILURE_DESCRIPTION),
  LARGE_SKIN_TUMOURS(LARGE_SKIN_TUMOURS_DESCRIPTION),
  LONG_TERM_MADNESS(LONG_TERM_MADNESS_DESCRIPTION),
  MAJOR_CONCUSSION(MAJOR_CONCUSSION_DESCRIPTION),
  MAJOR_LIVER_DAMAGE(MAJOR_LIVER_DAMAGE_DESCRIPTION),
  MAJOR_NEURALGIA(MAJOR_NEURALGIA_DESCRIPTION),
  MAJOR_ORGAN_NECROSIS(MAJOR_ORGAN_NECROSIS_DESCRIPTION),
  MINOR_CONCUSSION(MINOR_CONCUSSION_DESCRIPTION),
  MINOR_KIDNEY_DAMAGE(MINOR_KIDNEY_DAMAGE_DESCRIPTION),
  MINOR_DISFIGUREMENT(MINOR_DISFIGUREMENT_DESCRIPTION),
  MINOR_HEADACHES(MINOR_HEADACHES_DESCRIPTION),
  MINOR_INTERNAL_INJURY(MINOR_INTERNAL_INJURY_DESCRIPTION),
  MINOR_LIVER_DAMAGE(MINOR_LIVER_DAMAGE_DESCRIPTION),
  MINOR_NAUSEA(MINOR_NAUSEA_DESCRIPTION),
  MINOR_NEURALGIA(MINOR_NEURALGIA_DESCRIPTION),
  MINOR_ORGAN_NECROSIS(MINOR_ORGAN_NECROSIS_DESCRIPTION),
  MUSCLE_SPASMS(MUSCLE_SPASMS_DESCRIPTION),
  MUSCULAR_BREAKDOWN(MUSCULAR_BREAKDOWN_DESCRIPTION),
  NAUSEA(NAUSEA_DESCRIPTION),
  NECROTIC_STENCH(NECROTIC_STENCH_DESCRIPTION),
  NECROTIC_DISCOLOURATION(NECROTIC_DISCOLOURATION_DESCRIPTION),
  FESTERING_WOUND(FESTERING_WOUND_DESCRIPTION),
  ORGAN_DAMAGE(ORGAN_DAMAGE_DESCRIPTION),
  PARTIAL_BLINDNESS(PARTIAL_BLINDNESS_DESCRIPTION),
  PARTIAL_DEAFNESS(PARTIAL_DEAFNESS_DESCRIPTION),
  PHOBIA(PHOBIA_DESCRIPTION),
  PIERCED_STOMACH(PIERCED_STOMACH_DESCRIPTION),
  SECOND_DEGREE_BURNS(SECOND_DEGREE_BURNS_DESCRIPTION),
  SEVERE_BRUISING(SEVERE_BRUISING_DESCRIPTION),
  SEVERE_HEADACHES(SEVERE_HEADACHES_DESCRIPTION),
  SHORT_TERM_MADNESS(SHORT_TERM_MADNESS_DESCRIPTION),
  SMALL_SKIN_TUMOURS(SMALL_SKIN_TUMOURS_DESCRIPTION),
  SPIRITUAL_INJURY(SPIRITUAL_INJURY_DESCRIPTION),
  SYSTEMIC_DAMAGE(SYSTEMIC_DAMAGE_DESCRIPTION),
  THIRD_DEGREE_BURNS(THIRD_DEGREE_BURNS_DESCRIPTION),
  THROAT_INJURY(THROAT_INJURY_DESCRIPTION),
  UNHARMED(UNHARMED_DESCRIPTION),
  VERTIGO(VERTIGO_DESCRIPTION),
  WEAK_PERSONA(WEAK_PERSONA_DESCRIPTION),
  WITHERED_HAND(DESTROYED_HAND_DESCRIPTION),
  WITHERED_FOOT(DESTROYED_FOOT_OR_LEG_DESCRIPTION),
  INVALID_INJURY(INVALID_INJURY_DESCRIPTION)
  ;

  private String description;

  InjuryType(String description) {
    this.description = description;
  }

  public String getDescription() {
    return this.description;
  }

  public String getDescriptionFormatted() {
    String output = getNameFormatted();
    return output + ": " + this.description;
  }

  public String getNameFormatted() {
    String[] words = this.name().split("_");
    List<String> outputWords = new ArrayList<>();
    for(String word : words) {
      word = word.toLowerCase();
      outputWords.add(java.lang.Character.toString(word.charAt(0)).toUpperCase().concat(word.substring(1)));
    }
    return String.join(" ", outputWords);
  }

  @Override
  public String toString() {
    return getNameFormatted();
  }
}


